apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "metrics-client.fullname" . }}
  labels:
    app: {{ template "metrics-client.name" . }}
    chart: {{ template "metrics-client.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "metrics-client.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "metrics-client.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.pure1unplugged.image.repository }}:{{ .Values.global.pure1unplugged.image.tag }}"
          imagePullPolicy: {{ .Values.global.pure1unplugged.image.pullPolicy }}
          command: ["pure1-unplugged-metrics-client"]
          env:
            - name: PURE_DISCOVERY_TYPE
              value: pure1
            - name: PURE_DISCOVERY_PURE1_HOST
              value: pure1-unplugged-api-server
            - name: ELASTIC_HOST
              value: pure1-unplugged-elasticsearch-client:9200
            - name: ELASTIC_METRICS_RETENTION_PERIOD
              value: "{{ .Values.global.pure1unplugged.metricRetentionPeriod }}"
            - name: ELASTIC_ALERTS_RETENTION_PERIOD
              value: "{{ .Values.global.pure1unplugged.alertRetentionPeriod }}"
            - name: ELASTIC_ERROR_LOG_RETENTION_PERIOD
              value: "{{ .Values.global.pure1unplugged.errorLogRetentionPeriod }}"
            - name: ELASTIC_STAGE_TIMER_RETENTION_PERIOD
              value: "{{ .Values.global.pure1unplugged.timerLogRetentionPeriod }}"
            - name: ELASTIC_FA_VOLUME_METRIC_COLLECTION_PERIOD
              value: "{{ .Values.global.pure1unplugged.faVolumeCollectionPeriod }}"
            - name: ELASTIC_FB_VOLUME_METRIC_COLLECTION_PERIOD
              value: "{{ .Values.global.pure1unplugged.fbVolumeCollectionPeriod }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
