apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "api-server.fullname" . }}
  labels:
    app: {{ template "api-server.name" . }}
    chart: {{ template "api-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "api-server.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "api-server.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: secret-manager
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.pure1unplugged.image.repository }}:{{ .Values.global.pure1unplugged.image.tag }}"
          imagePullPolicy: {{ .Values.global.pure1unplugged.image.pullPolicy }}
          command: [ "pure1-unplugged-api-server" ]
          env:
            - name: ELASTIC_CLIENT_HOST
              value: pure1-unplugged-elasticsearch-client:9200
          ports:
            - name: ds-api-port
              port: 8080
              containerPort: 8080
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
