apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dex.fullname" . }}
  labels:
    app: {{ include "dex.name" . }}
    chart: {{ include "dex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
    config.yaml: |
        expiry:
          idTokens: {{ .Values.tokenTTL }}
        issuer: https://{{ .Values.global.publicAddress }}/dex
        storage:
          type: kubernetes
          config:
            inCluster: true
        web:
          http: 0.0.0.0:32000
        telemetry:
          http: 0.0.0.0:5558
        
        frontend:
          theme: "pure"
        
        logger:
          level: "debug"
          format: "text"
  
        connectors:
{{ toYaml .Values.connectors | indent 10}}

        staticClients:
        - id: pure1-unplugged
          redirectURIs:
          - https://{{ .Values.global.publicAddress }}/auth/callback
          name: 'Pure1 Unplugged'
          secret: ZXhhbXBsZS1hcHAtc2VjcmV0

        {{- if .Values.staticPasswords }}

        enablePasswordDB: true
        staticPasswords:
{{ toYaml .Values.staticPasswords | indent 8}}
        {{- else }}
        enablePasswordDB: false
        {{- end }}