apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "dex.fullname" . }}
  labels:
    app: {{ include "dex.name" . }}
    chart: {{ include "dex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dex.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "dex.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "dex.fullname" . }}
      volumes:
        - name: config
          configMap:
            name: {{ include "dex.fullname" . }}
            items:
            - key: config.yaml
              path: config.yaml
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.pure1unplugged.image.repository }}:{{ .Values.global.pure1unplugged.image.tag }}"
          imagePullPolicy: {{ .Values.global.pure1unplugged.image.pullPolicy }}
          command: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]
          ports:
            - name: http
              containerPort: 32000
              protocol: TCP
          volumeMounts:
          - name: config
            mountPath: /etc/dex/cfg
          {{- if .Values.enableGithubConnector}}
          env:
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-client
                  key: client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-client
                  key: client-secret
          {{- end}}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
