apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dex.fullname" . }}
  labels:
    app: {{ include "dex.name" . }}
    chart: {{ include "dex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "dex.fullname" . }}
  labels:
    app: {{ include "dex.name" . }}
    chart: {{ include "dex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: ["dex.coreos.com"] # API group created by dex
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create"] # To manage its own resources, dex must be able to create customresourcedefinitions
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dex.fullname" . }}
  labels:
    app: {{ include "dex.name" . }}
    chart: {{ include "dex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dex.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dex.fullname" . }} # Service account assigned to the dex pod, created above
    namespace: {{ .Release.Namespace }}  # The namespace dex is running in
