- name: pure1-unplugged infra setup
  hosts: all
  tasks:
  ##### Selinux config #####
  - name: selinux config
    selinux:
      policy: targeted
      state: enforcing

  ##### Network config #####
  - name: enable br_netfilter kernel module
    modprobe:
      name: br_netfilter
      state: present

  - name: set ipv6 bridge-nfs-call-ip6tables
    sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present
      sysctl_set: yes
      reload: yes

  - name: set ipv4 bridge-nfs-call-iptables
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present
      sysctl_set: yes
      reload: yes

  - name: get long hostname
    shell: hostname --long
    register: full_hostname_shell_output

  - set_fact:
      full_hostname: "{{ full_hostname_shell_output.stdout }}"

  - name: get short hostname
    shell: hostname --short
    register: short_hostname_shell_output

  - set_fact:
      short_hostname: "{{ short_hostname_shell_output.stdout }}"

  - name: add hostname to /etc/hosts
    lineinfile:
      dest=/etc/hosts
      line='127.0.0.1 localhost localhost.localdomain {{ full_hostname }} {{ short_hostname }}'
      regexp='^127\.0\.0\.1'
      insertafter='^127\.0\.0\.1'
      state=present

  ##### Firewall config #####
  - name: enable firewalld service
    shell: systemctl enable firewalld

  - name: reload firewalld service
    shell: systemctl daemon-reload

  - name: start firewalld
    systemd:
      name: firewalld
      enabled: true
      state: started

  - name: enable https service with firewall
    firewalld:
      service: https
      permanent: yes
      immediate: yes
      state: enabled

  - name: enable ssh service with firewall
    firewalld:
      service: ssh
      permanent: yes
      immediate: yes
      state: enabled

  ##### Swap config #####
  - name: Remove swapfile from /etc/fstab
    mount:
      name: swap
      fstype: swap
      state: absent

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  ##### Docker config #####
  - name: ensure /etc/docker exists
    file:
      path: /etc/docker
      state: directory
      mode: 0755

  - name: update /etc/docker/daemon.json
    template:
      src: templates/docker-daemon.json.j2
      dest: /etc/docker/daemon.json

  - name: ensure docker service directory exists
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
      mode: 0755

  - name: enable docker service
    shell: systemctl enable docker

  - name: reload docker service
    shell: systemctl daemon-reload

  - name: bounce the docker service to ensure it has correct daemon.json
    systemd:
      name: docker
      enabled: true
      state: restarted

  ##### Kubelet config #####

  # Don't start the kubelet service yet, it will only go into an error state until `kubeadm init`
  # just make sure it is enabled and loaded

  - name: enable kubelet service
    shell: systemctl enable kubelet

  - name: reload kubelet service
    shell: systemctl daemon-reload

  ##### helm #####
  - name: install helm bin
    copy:
      src: /opt/pure1-unplugged/infra/helm/helm
      dest: /usr/bin/helm
      owner: root
      group: root
      mode: preserve

  ##### Yum Repos #####
  - name: clear existing repos
    file:
      path: /etc/yum.repos.d/
      state: "{{ item }}"
    with_items:
      - absent
      - directory

  - name: install disabled centos base repo
    template:
      src: templates/CentOS-Base.repo.j2
      dest: /etc/yum.repos.d/CentOS-Base.repo

  - name: install pure1-unplugged media repo
    template:
      src: templates/Pure1-Unplugged-Media.repo.j2
      dest: /etc/yum.repos.d/Pure1-Unplugged-Media.repo

  ##### udev rules #####
  - name: install pure1-unplugged iso udev rule
    template:
      src: templates/90-pure1-unplugged-media-by-label-auto-mount.rules
      dest: /etc/udev/rules.d/90-pure1-unplugged-media-by-label-auto-mount.rules
