apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "elastic-setup.fullname" . }}
  labels:
    # The "heritage" label is used to track which tool deployed a given chart.
    # It is useful for admins who want to see what releases a particular tool
    # is responsible for.
    heritage: {{ .Release.Service }}
    # The "release" convention makes it easy to tie a release to all of the
    # Kubernetes resources that were created as part of that release.
    release: {{ .Release.Name }}
    # This makes it easy to audit chart usage.
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "elastic-setup.name" . }}
    product: "Pure1-Unplugged"
spec:
  backoffLimit: 16
  activeDeadlineSeconds: 1800
  template:
    metadata:
      name: {{ template "elastic-setup.fullname" . }}
      labels:
        release: {{ .Release.Name }}
        app: {{ template "elastic-setup.name" . }}
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: post-install-job
          image: {{ .Values.global.pure1unplugged.image.repository }}:{{ .Values.global.pure1unplugged.image.tag }}
          imagePullPolicy: {{ .Values.global.pure1unplugged.image.pullPolicy }}
          command: [ "./kibana-files/kibana_setup.sh" ]
