# The service account to add to the auth server pod
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager
---
# The role to allow secret CRUD
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ .Release.Namespace }}
  name: secret-rw
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "delete", "update"]
---
# Bind the role to the account
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: secret-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-rw
subjects:
- kind: ServiceAccount
  name: secret-manager
  namespace: {{ .Release.Namespace }}
